name: mucklet_chatbot
description: The chatbot that makes the librarian work.
version: 1.0.0
homepage: https://github.com/farcaller/mucklet-chatbot
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dotenv: ^4.0.1
  prometheus_client: ^1.0.0
  res_client: ^0.8.0
  glog: ^1.0.1
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  yaml: ^3.1.1
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
