name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/farcaller/mucklet-chatbot
        # generate Docker tags based on the following events/attributes
        tags: |
          type=sha
          
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to GHCR
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: "${{ github.repository_owner }}"
        password: "${{ secrets.GH_TOKEN }}"
    
    - name: Build and push 
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
